### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Andrew2a1** [Andrew2a1/LabController#1]
Funkcjonalności:
- [x] Wyświetlanie wartości wyjściowej
- [x] Zadawanie wartości na wejściu
- [x] Obiekt regulacji (pojemnik z substancją + grzanie i chłodzenie)
- [x] Regulator (trójpołożeniowy)
- [x] Wprowadzanie zakłócenia

Interfejs użytkownika:
- [x] Ikonki
- [x] Animacje
- [x] Interfejs graficzny

Historyjki:
1. Po uruchomieniu aplikacji chciałbym widzieć, jaka jest obecna temperatura
2. Chciałbym mieć możliwość śledzenia zmian temperatury
3. Chciałbym znać trend (czy wzrasta, czy opada)  i szybkość zmian temperatury
4. Chciałbym mieć możliwość regulacji temperatury
5. Chciałbym, aby można było wyłączyć proces regulacji
6. Chciałbym wiedzieć, czy regulator chłodzi, czy grzeje (i jak mocno)
7. Chciałbym znać granice regulacji układu

**Comment by Andrew2a1** [comment]
Diagram UML klas symulacji:
![obraz](https://user-images.githubusercontent.com/32133486/98158697-9fa51780-1edb-11eb-918a-bc80db13604b.png)

**Comment by Uszczi** [comment]
> Diagram UML klas symulacji:
> ![obraz](https://user-images.githubusercontent.com/32133486/98238207-5352e980-1f66-11eb-9ce7-8b9845f5d73c.png)

![Uploading 98238207-5352e980-1f66-11eb-9ce7-8b9845f5d73c.png…]()

**Comment by Uszczi** [comment]
> Diagram UML klas symulacji:
> ![obraz](https://user-images.githubusercontent.com/32133486/98238207-5352e980-1f66-11eb-9ce7-8b9845f5d73c.png)

![98238207-5352e980-1f66-11eb-9ce7-8b9845f5d73c](https://user-images.githubusercontent.com/45439812/98363570-74334180-202f-11eb-875c-f4e686f3440d.png)
